- peer/connector.go
- peer/rpcs.go
- peer/setup.go
- peer/subscriber.go
- rpc/node.go
two new rpc calls for tracing connections
> [peer,rpc] add new rpc apis for collecting addresses of connectors and subscribers

- rpc/server.go
- rpc/transaction.go
> [transaction] add a new rpc api for query transaction status

- constants/constants.go
- peer/subscriber.go
- reservoir/background.go
- reservoir/issues.go
- reservoir/setup.go
- reservoir/transfer.go
- rpc/bitmarks.go
* add one more payload for "issues" messages
* store an issue to the verified set by checking `isVerified` flag in StoreIssues function
> [reservoir,constants,peer,rpc] add the mechanism of transaction rebroadcasting

- command/bitmark-cli/check_commands.go
- command/bitmark-cli/run-create.go
- fault/fault.go
- transactionrecord/asset_test.go
- transactionrecord/pack.go
- transactionrecord/transaction.go
- transactionrecord/unpack.go
In this PR, we implement the feature to make name field in the asset record optional.
> Make the asset name optional

- block/setup.go
- fault/fault.go
In this pull request, we implement a mechanism to validate the index db.
> Implement block validation

- block/setup.go
- fault/fault.go
In this PR, we add the following improvements
1. further checks for transaction provenance related table.
2. refactor some validation functions
3. add documentations
> Implement block validation with provenance check

- zmqutil/client.go
- zmqutil/client_test.go
This modification adds method for disconnect then reconnect to existing zmq socket
> Zmqutil reconnect socket

- command/recorderd/config_reader.go
- command/recorderd/config_reader_test.go
- command/recorderd/configuration.go
- command/recorderd/file_watcher.go
- command/recorderd/file_watcher_test.go
- command/recorderd/job_calendar.go
- command/recorderd/job_calendar_test.go
- command/recorderd/job_manager.go
- command/recorderd/job_manager_test.go
- command/recorderd/main.go
- command/recorderd/proofer.go
- command/recorderd/proofer_test.go
- command/recorderd/recorderd.conf.sample
- command/recorderd/subscriber.go
- go.mod
This pull request adds feature to dynamically control hasing power and time. After change config file, cpu power usage and schedule time will be applied within 1 minute.
New settings `max_cpu_usage` stands for percentage of cpu power used for hashing. Maximum range is 100.
New settings `calendar` stands for schedule time for hashing.
> Recorderd resource limiter

- command/recorderd/config_reader.go
use absolute path for config to read
> [recorderd] fix configuration path

- command/bitmarkd/main.go
In case reservoir-cache file not exist may happen
> [reservoir] exclude error case of reservoir cache file not exist

- reservoir/expiration.go
- reservoir/sharegrant.go
- reservoir/shareswap.go
- reservoir/transfer.go
Fix Transaction does not expire issue
> Transfer expiry

- block/setup.go
This PR does the following
- Fix crash issue when block validation is running with the tx is share
> [bitmarkd] Fix crash on block validation

- announce/nodeslookup.go
> [bitmarkd] Optimize get TTL record from server

- block/recovery.go
> fix-trx-not-commit: add missing transaction commit

- announce/announcer.go
- announce/peer.go
- peer/connector.go
- peer/upstream/setup.go
rename the register and send update peerTimeStamp through the message bus
> Refactor Upstream register to connected

- messagebus/queue_test.go
> add-missing-label: add label

- command/bitmark-cli/run-sign.go
> [command] Fix wrong format

- account/private.go
- account/private_test.go
> [bitmarkd] support import seed for 12 words recovery phrase

- peer/upstream/setup.go
> [bitmarkd] Change locking for better performance 

- block/blockstore.go
- block/delete.go
- block/store.go
- blockrecord/header.go
- peer/connector.go
- peer/upstream/upstream.go
- peer/voting/voting.go
Following bugs are fixed
- when block delete, difficulty should updated when over adjust blocks
- connector should enter fork-detect when better chain is found
> Fix node not sync

- peer/connector.go
this modification fix following 2 bus:
1. initial connection client count is doubled
2. when connection sampling state with less clients, enter connection process
> Fix connection number

- blockrecord/header.go
- blockrecord/validator.go
- blockrecord/validator_test.go
Difficulty applied start from header version 4
> [blockrecord] modify difficulty applied version to 4

- blockrecord/validator.go
- blockrecord/validator_test.go
- difficulty/difficulty.go
- difficulty/difficulty_test.go
Fix difficulty calculation, currently it will easily multiply by 4 because of wrong ratio
> [difficulty] fix difficulty calculation

- difficulty/difficulty.go
- difficulty/difficulty_test.go
> [difficulty] fix hash rate calculation

- payment/p2p.go
Currently, the `getPeer` function will return a peer until it get one. However, it would blocks the flow of `sync` function which makes it not able to close gracefully and stops the shutdown flow.
To solve this, we add a retry time for `getPeer` to make it stops and then the `sync` function will be able to continue it flow.
> Fix the `sync` function getting stuck by the `getPeer`

- p2p/p2p.go
We should **ONLY** limit the broadcasting of peer and rpc packet for client node.
> Fix incorrect broadcast behavior of client node

- p2p/p2pUpstream.go
`network.Stream` is an interface. It is not a good practice to use pointer of interface. It makes you convert it back and forth in code.
We can simply use the pointer of a struct as a parameter directly. It is simple and clear.
> Reduce the code complexity by not using pointer of interface

- proof/publisher.go
- proof/setup.go
- testing/create-node-users.sh
- testing/generate-bitmarkd-configuration
- testing/make-blockchain
- testing/restart-all-bitmarkds
- testing/run-bitmarkd
update libp2p branch to master branch:bd82bb1
> Libp2p update to bd82bb1

- command/bitmarkd/bitmarkd.conf.sub
- proof/publisher.go
- proof/setup.go
- proof/submission.go
make internal hash optional for local
- configuration add
local_use_internal_hash = false,
> [proof]make internal hash for local optional

- p2p/node.go
- p2p/p2p_test.go
- p2p/registration.go
- p2p/registration_test.go
- p2p/setup.go
straighten out the locking, separating RLock/RUnlock and Lock/Unlock appropriately
Signed-off-by: Christopher Hall <hsw@bitmark.com>
> [p2p] fixes for R/W locking

- .circleci/config.yml
- command/bitmarkd/main.go
- consensus/api.go
- consensus/consensus_test.go
- consensus/machine.go
- consensus/metricsVoting.go
- consensus/setup.go
- currency/chain.go
- reservoir/loadsave_test.go
- reservoir/restorer.go
- reservoir/setup.go
- rpc/bitmark/bitmark.go
- rpc/bitmark/bitmark_test.go
- rpc/server/server.go
Signed-off-by: Christopher Hall <hsw@bitmark.com>
> [.circleci] add go vet to catch locking problems

- command/bitmarkd/main.go
- reservoir/loadsave_test.go
- reservoir/restorer.go
- reservoir/setup.go
- rpc/server/server.go
fix `reservoir` interface not properly initialized, and also wrong database specified
> Fix reservoir handles
