command/bitmark-info/README.md
command/bitmark-info/main.go

Add a new command, `bitmark-info`, for fetch RPC response from bitmarkd.

[command] bitmark-info

---

announce/announcer.go
announce/setup.go
avl/avl_test.go
avl/search.go
avl/setup.go

The main idea is to search nodes in trees whose depth are 2.
If a node is located in a depth 2 subtree, we calc the order of the node in the tree. Then, we try to finds nodes with the same order in the rest of sibling depth 2 trees and connects to them.
Besides, to ensure that each nodes could have a whole view of all nodes. We broadcast nodes in a round-robin manner so every nodes can eventually get all its peers in a network.

Add extra connections for nodes

---

peer/client.go
rpc/node.go

`return err` -> `return nil`
In this case `err` is a `nil` type anyways, might as well just return `nil`.

Return nil for readability

---

payment/background.go
peer/listener.go

The log level of tcp events should belong to debug. The info log should be normal information. Put this messages in will make info level be useless.

Change log level of tcp events into debug

---

command/bitmarkd/bitmarkd.conf.sample
command/bitmarkd/commands.go

1. `gen-proof-identity` will generate signing keys for both livenet and testnet
2. The lua config can read the required one based on `M.chain` (Reference: http://lua-users.org/wiki/TernaryOperator)

fix gen-proof-identity command

---

block/setup.go
command/bitmark-cli/rpccalls/grant.go
command/bitmark-cli/rpccalls/swap.go
rpc/httphandler.go
rpc/node.go

This PR do the following
- Add latest block hash to response in HTTP API `bitmarkd/details`
- Add latest block hash to response in RPC call `Node.Info`

[Bitmarkd] Add latest block hash in HTTP and RPC response

---

.gitignore
announce/nodeslookup.go
announce/peer.go
announce/setup.go
go.mod
go.sum
peer/connector.go
peer/upstream/setup.go

This PR do following:
Reference: https://bitmarkinc.monday.com/boards/215309468/pulses/212067159

[bitmarkd] Active connection timeout

---

messagebus/queue.go
messagebus/queue_test.go
peer/upstream/setup.go
publish/broadcaster.go

[bitmarkd] Queue overflow in peer protocol

---

peer/upstream/setup.go
util/canonical.go
zmqutil/client.go

This PR do the following
Change:
- I also delete the `poller` in `zmqutil/client.go`. The reason is to avoid concurrent polling and sending/receiving from same socket.

[bitmarkd] Mitigate connection loss in upstream 

---

account/private.go
command/bitmarkd/commands.go

[bitmarkd] support generating proof identity v2 seed as default

---

announce/nodeslookup.go

[bitmarkd] Better for getting TTL record

---

block/store.go
blockrecord/header.go
blockrecord/validator.go
command/bitmarkd/main.go
storage/handle.go
zmqutil/client.go

Fix bitmarkd not able to sync when a bitmarkd just start and difficulty is not reset.
Also fix a performance problem that if a block with same height but with smaller digest, it comes in will be rejected. Previously every block is assumes to be higher than local one, as consensus is modified, same height block could still comes.

Fix block not sync

---

block/delete.go
block/store.go
blockrecord/header.go
blockrecord/validator.go
blockrecord/validator_test.go
difficulty/difficulty.go
difficulty/difficulty_test.go
proof/publisher.go

Incoming block difficulty should be check and apply only when other nodes considering difficulty.
The bug happens that some functions are coupled together (need to check header version before checking difficulty). To avoid unexpectedly missing function call, this modification moves difficulty header checking into difficulty validation functions.

Fix incoming block not apply difficulty

---

announce/nodeslookup.go
announce/peer.go
announce/peer_test.go
announce/rpc.go
announce/store.go

When bitmarkd starts, it will add all peers from cache file. This modification will only add those peers that are not expired. Also refactor some functions with similar logic

Import peer not expired

---

peer/connector.go
util/canonical.go
util/canonical_test.go

1. Add two more test cases about checking missing ports for `NewConnection`.
2. When the connector wants to take action on its clients, don't do anything if the client is nil.

ensure port is provided and only take action when client is not nil

---

command/bitmarkd/bitmarkd.conf.sample
command/bitmarkd/bitmarkd.conf.sub
currency/chain.go
currency/chain_test.go
payment/p2p.go
payment/p2p_test.go
payment/setup.go
storage/payment.go
storage/payment_test.go

Since bitmarkd has an option to run a local chain, it is better to run it with a currency chains in regression test mode. In this PR, the bitmarkd will use `regtest` parameter of currency chains if the chain is set to `local`. In `regtest` mode, the client checkpoint will start from the genesis hash that is defined from bitcoin and litecoin network.
There is no DNS seed for bitcoin / litecoin regtest network. Thus, a new config is added in order to assign dedicated bitcoin and litecoin nodes.

Add regtest mode for local chain and be able to assign dedicate nodes

---

command/bitmarkd/bitmarkd.conf.sub
command/bitmarkd/configuration.go
payment/p2p.go
payment/p2p_test.go
payment/setup.go

In this PR, we create a configuration for assign peer cache folders. 
By default, it uses the directory that runs bitmarkd to save the cache. Since the file name is fixed in btcd program, it would have problems like peer.json is override by accident. 
With the change, the `peers.json` for bitcoin and litecoin by default. Is is also possible to change it to your preferred places.

Make p2p peer cache folder configurable

---

currency/chain.go

Bitmarkd now fails to negotiate with litecoind node since the number is set to bitcoin one. This PR is going to fix the number

Fix incorrect magic number for litecoin mainnet

---

announce/tagparsing.go
command/bitmarkd/bitmarkd.conf.sample
command/bitmarkd/commands.go
p2p/p2p.go
util/peerKey.go

In the PR, it fixes the `dns-txt` command and update `gen-peer-identity` with the libp2p key.

Fix commands for `dns-txt` and `gen-peer-identity`

---

command/bitmarkd/bitmarkd.conf.sub
command/bitmarkd/commands.go

Since we are using the zeromq for publish and subscribe, we have to separate the key between libp2p and zeromq. The `gen-peer-identity` command will now create those keys at the same time.

Add publishing keypairs

---

block/store.go
blockdigest/digest.go
blockdigest/digest_test.go
blockrecord/validator.go
blockrecord/validator_test.go
fault/fault.go
proof/internal_hasher.go
proof/internal_hasher_test.go
proof/publisher.go
proof/queue.go
proof/setup.go
proof/submission.go

This modification adds an internal hasher which is used when chain is local. The advantages of internal hasher is to faster local development/testing, so that whatever the block hash is always valid.
Following changes are made:
1. When chain is local, block digest checking is always success
2. internal hasher is started when chain is local, thus no longer needs extra program recorderd

Regression test

---

testing/bm-tester

bm-tester run failed because the top command is different from FreeBSD to Ubuntu.

[testing]fix top command various in different os

---

proof/proof_test.go
proof/setup.go
proof/submission.go
rpc/node.go

This patches counts fail/success block from current node. The value stores in memory and reset whenever node is restarted

Count mined block

---

announce/announce_test.go
announce/announcer.go
announce/setup.go
announce/storepeers.go
command/bitmarkd/bitmarkd.conf.sub
command/bitmarkd/configuration.go
command/bitmarkd/main.go
p2p/connector.go
p2p/listener.go
p2p/metricsVoting.go
p2p/multicastSub.go
p2p/nodeImpl.go
p2p/p2p.go
p2p/p2pUpstream.go
p2p/p2p_test.go

DNS Peers Only Feature
------------------------------
Make this node a  hidden node and its peer tree has only nodes in DNS records.  Mainly for CTBC
CHANGE-LOG
--------------------------
Configuration: dns_peers_only in bitmarkd.conf
Peer tree:  only has peers in DNS records
RPC client: no changes
Peerstore: disable loading peers.json to avoid none DNS nodes
Broadcasting: peer and RPC does not broadcast themself
exhaustive connection: send all tree nodes to a P2P module.  The feature is added because peer-tree does not change unless DNS records have changed. The "determineConnection" may not pick-up all nodes so a node may not be picked. This may be an issue when a node is under or equal to  minimum count of voting mechanism

Libp2p dns peer

---

block/store.go
blockdigest/digest.go
blockdigest/digest_test.go
blockrecord/validator.go
blockrecord/validator_test.go
command/bitmarkd/bitmarkd.conf.sub
command/bitmarkd/configuration.go
debian/changelog
doc/release-note-template.md
fault/fault.go
p2p/nodeImpl.go
p2p/p2p.go
p2p/p2p_test.go
p2p/pack.go
proof/internal_hasher.go
proof/internal_hasher_test.go
proof/proof_test.go
proof/publisher.go
proof/queue.go
proof/setup.go
proof/submission.go
release-notes.md
rpc/node.go
rpc/setup.go
testing/bm-tester

Rename node type from servant/client to server.client
+ Configuration file:  server/client
``` 
-- set node types (server|client)    
-    nodetype = "server",
```
+  P2P define NodeType  variable has a   nodeType type
```
type nodeType string
NodeType     nodeType
```
+ Define const for availible choices
```
const (
ServerNode nodeType = "server"
ClientNode nodeType = "client"
)
```

Libp2p rename to server

---

command/bitmarkd/bitmarkd.conf.sub
rpc/setup.go

freeBSD and linux in tls and zeroMQ library level will do ipv4 to ipv6 mapping. 
For listening all on both ipv4 and ipv6 in freeBSD and Linux, 
We make it listen on IPV6
This affects on : 
Configuration Add port 
RPC TLS network type
Peer package will not be affected because configuration has already taken care of it

fix  ipv4 to ipv6 mapping issue on different OS

---

command/bitmarkd/bitmarkd.conf.sub
command/bitmarkd/commands.go
p2p/node.go
p2p/p2p_test.go
p2p/setup.go

renamed from private to secret to avoid confusion with
public/private keys pairs in separate files
Signed-off-by: Christopher Hall <hsw@bitmark.com>

[command,p2p] rename the peer key configuration item

---

block/blockstore.go

This is a part of fix of  [libp2p] traffic load is unexpected #146 
Fix forcing flooding-broadcasting in block broadcasting
only the node which generates the block using gossip-broadcasting to send it

Libp2p resend block

---

README.md

If there is no `"` command cannot be executed normally

[Fix doc] Wrong example code
